# Generated by Django 5.0.7 on 2024-07-21 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_insurance', models.CharField(max_length=300, verbose_name='type_of_insurance')),
            ],
            options={
                'verbose_name': 'Insurance',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name_client')),
                ('surname', models.CharField(max_length=300, verbose_name='surname_client')),
                ('age', models.CharField(max_length=100, verbose_name='age_client')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_value', to='records.insurance', verbose_name='Insurance')),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_plus_value', to='records.insurance', verbose_name='Value')),
            ],
        ),
    ]
