# Generated by Django 5.0.7 on 2024-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_insurance_options_remove_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.AutoField(default=30300, primary_key=True, serialize=False),
        ),
    ]
