# Generated by Django 5.0.7 on 2024-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_client_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
