# Generated by Django 5.0.7 on 2024-07-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='about_insurance',
            field=models.CharField(default='', max_length=600, verbose_name='about_insurance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_number',
            field=models.CharField(max_length=12),
        ),
    ]
