# Generated by Django 5.0.7 on 2024-08-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='value',
            field=models.CharField(default='', max_length=300, verbose_name='value'),
        ),
    ]
