# Generated by Django 5.0.7 on 2024-08-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_insurance_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='value',
        ),
        migrations.AddField(
            model_name='user',
            name='insurance',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.insurance', verbose_name='Insurance'),
        ),
    ]
