# Generated by Django 5.0.7 on 2024-08-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_insurance_value_user_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_value',
            field=models.FloatField(default=0, max_length=600, verbose_name='insurnace_value'),
        ),
    ]
