# Generated by Django 5.0.7 on 2024-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_insurance_insurance_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_value',
        ),
        migrations.AddField(
            model_name='user',
            name='insurance_value',
            field=models.FloatField(default=0, max_length=600, verbose_name='insurnace_value'),
        ),
    ]
