# Generated by Django 5.0.7 on 2024-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_remove_insurance_insurance_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_value',
            field=models.FloatField(default=0, max_length=600, verbose_name='insurnace_value'),
        ),
        migrations.AlterField(
            model_name='user',
            name='insurance_value',
            field=models.FloatField(default=0, max_length=600, verbose_name='insurance_value'),
        ),
    ]
